### ISSUE TITLE
Function logs new target version, but has no effect

### ISSUE THREAD

**Issue by Crossbow78** [shibayan/keyvault-certificate-rotation#13]
The setup:
* My function identity has the 'Contributor' role on my CDN profile, and has all certificate management (+get secrets/keys) access policies on the keyvault that holds the certificate.
* There is a new version of the SSL certificate available in the keyvault (and navigating to the corresponding CDN endpoint confirms that it's currently not using this latest version).

The issue:
* When I invoke the function, it properly lists the CDN endpoints in my profile, and also reports it will update to a new version:

> 2020-12-12T17:55:48.817 [Information] CDN Proflie: cdn-xxxx
2020-12-12T17:55:49.223 [Information] CDN Endpoint: cdn-xxxx
2020-12-12T17:55:49.865 [Information] Custom Domain: web-xxxx
2020-12-12T17:55:49.865 [Information] Vault Name: KV-xxxx
2020-12-12T17:55:49.865 [Information] Secret Name: wildcard-xxxx-com
2020-12-12T17:55:49.865 [Information] Secret Version: a46ed853cc7043exxxxxxxxxxxxxxxxxxxx
2020-12-12T17:55:49.936 [Information] Target Secret Version: dc3befbe594bxxxxxxxxxxxxxxxxxxxx

Invoking the function again results in exactly the same log, every time again...
And when I check my CDN profile, it's indeed still pointing at the old certificate version 'a46ed8....'

What could be going wrong with that final step of applying the change?

**Comment by shibayan** [comment]
There seems to be a problem while executing an update request to the CDN, is there an exception or error log in Application Insights?

Since API calls often take a long time, the process may be interrupted by Azure Functions timeouts.

And you can check the `Activity log` of the CDN to be updated. If the process is successful, you should see the `EnableCustomHttps` log.

![image](https://user-images.githubusercontent.com/1356444/102013315-8624a480-3d92-11eb-8b67-f761ce8b3d98.png)

**Comment by Crossbow78** [comment]
Good advice, I found some errors, but they still leave me clueless on how to proceed...

In Application Insights, I found a `CertificateClient.GetCertificate` that had a 401 response for a `GET /certificates/xxx`...
![image](https://user-images.githubusercontent.com/7549753/102022892-0eeb1280-3d8a-11eb-8506-d60fc659ae7a.png)

In the CDN profile activity log, there was an error:
```json
{
    "status": "Failed",
    "error": {
        "code": "ResourceOperationFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "CustomDomainSecureDeliveryInvalidKeyVaultSubscriptionId",
                "message": "The subscription ID of the Key Vault account is different from the subscription ID of the CDN profile."
            }
        ]
    }
}
```

Considering the error message above, I should mention that some resources have migrated to a different subscription a few months ago, but since then all components involved (Key Vault, CDN profile, and this certbot function) have been in one and the same subscription.

Note that a manual certificate version update in the CDN profile succeeded just fine, but the function keeps failing.
(and I still have another certificate update pending that allows me to test this issue)

**Comment by shibayan** [comment]
Thanks for the detailed information. Now I understand the cause.

Because Azure CDN maintain separate subscription ID and resource group name in their settings, moving a resource seems to result in an error that cannot be found.

![temp3](https://user-images.githubusercontent.com/1356444/102036106-59f63b80-3e05-11eb-8e1b-e0fcb1fff5a8.png)

I will release a modified version by the end of today!

**Comment by shibayan** [comment]
Initially, I thought about automatically updating the subscription ID and resource group name in the application, but unfortunately, I found that this was not possible.

The reason is that it is difficult to get the subscription ID and resource group name from the name of the Key Vault. Since additional RBAC settings are required to achieve this behavior, implementation would break existing applications.

Sorry, you will need to manually reconfigure your Key Vault certificate to CDN/Front Door if you moved your Key Vault subscription or resource group name.

After the reconfiguration, the update will be done automatically as before. This behavior will be described in the documentation.

**Comment by Crossbow78** [comment]
Your analysis makes total sense, it's interesting to learn about this shadow administration in the CDN profile.

In Azure Portal in the CDN endpoint custom domain UI, the source key vault was also not correctly populated in the dropdown, indeed suggesting a broken reference. After having updated the certificate manually, the key vault now properly shows in the dropdown. I'm confident that next update will be smooth and automated.

Thanks for your assistance.
